In [10]:
import numpy as np

arry1 = np.array([1, 2, 3, 4, 5])
arry2 = np.array([6, 7, 8, 9, 10])

result_addition = arry1 + arry2  # Element-wise addition of arrays
result_subtraction = arry1 - arry2 # Element-wise subtraction of arrays
result_multiplication = arry1 * arry2  # Element-wise multiplication of arrays
result_devision = arry1 / arry2  # Element-wise division of arrays

print("Addition Result:", result_addition)
print("Subtraction Result:", result_subtraction)
print("Multiplication Result:", result_multiplication)
print("Division Result:", result_devision)

Addition Result: [ 7  9 11 13 15]
Subtraction Result: [-5 -5 -5 -5 -5]
Multiplication Result: [ 6 14 24 36 50]
Division Result: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [11]:
import numpy as np

arry1 = np.array([1, 2, 3, 4, 5])

print(np.sqrt(arry1))  # Element-wise square root of the array
print(np.sum(arry1))  # Sum of all elements in the array
print(np.mean(arry1))  # Mean of the elements in the array
print(np.min(arry1))  # Minimum value in the array
print(np.max(arry1))  # Maximum value in the array

[1.         1.41421356 1.73205081 2.         2.23606798]
15
3.0
1
5


In [12]:
arr1 = np.array([[9,10,6],[8,12,20]])

print(arr1.size)  # count single element size
print(arr1.ndim)  # number of dimensions
print(arr1.shape)  # shape of the array(rows, columns)


6
2
(2, 3)


In [13]:
arr2 = np.array([1, 2, 3, True, 5.0, "Hello"])
print(arr2.dtype)



<U32


In [14]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr3[1,1]) # Accessing element at row 1, column 1
print(arr3[0, :]) # Accessing all elements in row 0
print(arr3[:, 1]) # Accessing all elements in column 1

5
[1 2 3]
[2 5]


In [15]:
arr2 = np.array([10, 20, 30, 40, 50, 1, 90, 100])

condition = arr2 > 20  # Create a boolean condition
print(condition)  # Print the condition array
# Use the condition to filter the array
# This will return elements where the condition is True
# For example, it will return elements greater than 20

filtered_arr = arr2[condition]  # Filter the array based on the condition

print(filtered_arr)

print(arr2[arr2 > 20])  # Directly filter and print elements greater than 20

print(arr2[(arr2 > 20) & (arr2 < 45)])  # Filter elements greater than 20 and less than 45

[False False  True  True  True False  True  True]
[ 30  40  50  90 100]
[ 30  40  50  90 100]
[30 40]


your given the following array representing to the body tempreture (celsius) of five petions or theree times (morning, afternoon, evening)

             morning   afternoon  evening
pation 1        31         30       28
pation 2        26         29       32
pation 3        26         24       37
pation 4        31         34       35
pation 5        28         31       30

identify and extract all tempercure reading grater than tha daily avarage tempreture using boolenan indexing

In [16]:
import numpy as np

temprature = np.array([[31, 30, 28],
                       [26, 29, 32],
                       [26, 24, 37],
                       [31, 34, 35],
                       [28, 31, 30]])

avarage_temp = np.mean(temprature)  

print(temprature[temprature > avarage_temp])

[31 32 37 31 34 35 31]


In [9]:
print(np.zeros((3, 4)))  # Create a 3x4 array filled with zeros
print(np.ones((2, 3)))   # Create a 2x3 array filled with ones
print(np.full((2, 2), 7))  # Create a 2x2 array filled with the value 7

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]


In [ ]:
# Create a 2x3 array filled with a 1,2,3
print(np.full((2,3),[1,2,3])) 

[[1 2 3]
 [1 2 3]]


In [23]:
print(np.empty((2, 3)))  # Create an empty 2x3 array

[[4.9e-324 9.9e-324 1.5e-323]
 [4.9e-324 9.9e-324 1.5e-323]]
